# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# imagePullSecret: codefresh-generated-r.cfcr.io-cfcr-default
image:
  repository: 336151728602.dkr.ecr.us-west-2.amazonaws.com/demochat
  tag: master
  pullPolicy: IfNotPresent
service:
  name: demochat
  type: LoadBalancer
  externalPort: 5000
  internalPort: 5000
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    # - minikube
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

mongodb:
  auth:
    rootPassword: password